color_scheme:
  colors:
  - {color: '#6750A4', name: Primary}
  - {color: '#EADDFF', name: Primary Container}
  - {color: '#FFFFFF', name: On Primary}
  - {color: '#21005E', name: On Primary Container}
  - {color: '#625B71', name: Secondary}
  - {color: '#E8DEF8', name: Secondary Container}
  - {color: '#FFFFFF', name: On Secondary}
  - {color: '#1E192B', name: On Secondary Container}
  - {color: '#7D5260', name: Tertiary}
  - {color: '#FFD8E4', name: Tertiary Container}
  - {color: '#FFFFFF', name: On Tertiary}
  - {color: '#370B1E', name: On Tertiary Container}
  - {color: '#B3261E', name: Error}
  - {color: '#FFFBFE', name: Background}
  - {color: '#FFFBFE', name: Surface}
  - {color: '#1C1B1F', name: On Background}
  - {color: '#1C1B1F', name: On Surface}
  - {color: '#E7E0EC', name: Surface Variant}
  - {color: '#49454E', name: On Surface Variant}
  - {color: '#79747E', name: Outline}
  - {color: 'rgba(28, 27, 31, 0.38)', name: On Disabled}
  - {color: 'rgba(28, 27, 31, 0.12)', name: Disabled Container}
  - {color: 'rgba(255, 255, 255, 0.08)', name: Light Overlay 1}
  - {color: 'rgba(255, 255, 255, 0.12)', name: Light Overlay 2}
  - {color: 'rgba(30, 25, 43, 0.08)', name: Dark Overlay 1}
  - {color: 'rgba(30, 25, 43, 0.12)', name: Dark Overlay 2}
  - {color: 'rgba(103, 80, 164, 0.05)', name: Primary Overlay 1}
  - {color: 'rgba(103, 80, 164, 0.08)', name: Primary Overlay 2}
  - {color: 'rgba(103, 80, 164, 0.11)', name: Primary Overlay 3}
  preset_groups:
  - name: Colour Scheme
    options:
    - colors:
      - {color: '#6750A4', name: Primary}
      - {color: '#EADDFF', name: Primary Container}
      - {color: '#FFFFFF', name: On Primary}
      - {color: '#21005E', name: On Primary Container}
      - {color: '#625B71', name: Secondary}
      - {color: '#E8DEF8', name: Secondary Container}
      - {color: '#FFFFFF', name: On Secondary}
      - {color: '#1E192B', name: On Secondary Container}
      - {color: '#7D5260', name: Tertiary}
      - {color: '#FFD8E4', name: Tertiary Container}
      - {color: '#FFFFFF', name: On Tertiary}
      - {color: '#370B1E', name: On Tertiary Container}
      - {color: '#B3261E', name: Error}
      - {color: '#FFFBFE', name: Background}
      - {color: '#FFFBFE', name: Surface}
      - {color: '#1C1B1F', name: On Background}
      - {color: '#1C1B1F', name: On Surface}
      - {color: '#E7E0EC', name: Surface Variant}
      - {color: '#49454E', name: On Surface Variant}
      - {color: '#79747E', name: Outline}
      - {color: 'rgba(28, 27, 31, 0.38)', name: On Disabled}
      - {color: 'rgba(28, 27, 31, 0.12)', name: Disabled Container}
      - {color: 'rgba(255, 255, 255, 0.08)', name: Light Overlay 1}
      - {color: 'rgba(255, 255, 255, 0.12)', name: Light Overlay 2}
      - {color: 'rgba(30, 25, 43, 0.08)', name: Dark Overlay 1}
      - {color: 'rgba(30, 25, 43, 0.12)', name: Dark Overlay 2}
      - {color: 'rgba(103, 80, 164, 0.05)', name: Primary Overlay 1}
      - {color: 'rgba(103, 80, 164, 0.08)', name: Primary Overlay 2}
      - {color: 'rgba(103, 80, 164, 0.11)', name: Primary Overlay 3}
      name: Material Light
    - colors:
      - {color: '#D0BCFF', name: Primary}
      - {color: '#4F378B', name: Primary Container}
      - {color: '#371E73', name: On Primary}
      - {color: '#EADDFF', name: On Primary Container}
      - {color: '#CCC2DC', name: Secondary}
      - {color: '#4A4458', name: Secondary Container}
      - {color: '#332D41', name: On Secondary}
      - {color: '#E8DEF8', name: On Secondary Container}
      - {color: '#EFB8C8', name: Tertiary}
      - {color: '#633B48', name: Tertiary Container}
      - {color: '#492532', name: On Tertiary}
      - {color: '#FFD8E4', name: On Tertiary Container}
      - {color: '#F2B8B5', name: Error}
      - {color: '#1C1B1F', name: Background}
      - {color: '#1C1B1F', name: Surface}
      - {color: '#E6E1E5', name: On Background}
      - {color: '#E6E1E5', name: On Surface}
      - {color: '#49454F', name: Surface Variant}
      - {color: '#CAC4D0', name: On Surface Variant}
      - {color: '#938F99', name: Outline}
      - {color: 'rgba(230, 225, 229, 0.38)', name: On Disabled}
      - {color: 'rgba(230, 225, 229, 0.12)', name: Disabled Container}
      - {color: 'rgba(232, 222, 248, 0.08)', name: Light Overlay 1}
      - {color: 'rgba(232, 222, 248, 0.12)', name: Light Overlay 2}
      - {color: 'rgba(232, 222, 248, 0.08)', name: Dark Overlay 1}
      - {color: 'rgba(232, 222, 248, 0.12)', name: Dark Overlay 2}
      - {color: 'rgba(208, 188, 255, 0.05)', name: Primary Overlay 1}
      - {color: 'rgba(208, 188, 255, 0.08)', name: Primary Overlay 2}
      - {color: 'rgba(208, 188, 255, 0.11)', name: Primary Overlay 3}
      name: Material Dark
    - colors:
      - {color: '#1EB980', name: Primary}
      - {color: '#005235', name: Primary Container}
      - {color: '#003824', name: On Primary}
      - {color: '#73FBBC', name: On Primary Container}
      - {color: '#B4CCBC', name: Secondary}
      - {color: '#364B3F', name: Secondary Container}
      - {color: '#20352A', name: On Secondary}
      - {color: '#D0E8D8', name: On Secondary Container}
      - {color: '#A4CDDD', name: Tertiary}
      - {color: '#234C5A', name: Tertiary Container}
      - {color: '#063542', name: On Tertiary}
      - {color: '#C0E9FA', name: On Tertiary Container}
      - {color: '#D64D47', name: Error}
      - {color: '#191C1A', name: Background}
      - {color: '#191C1A', name: Surface}
      - {color: '#E1E3DF', name: On Background}
      - {color: '#E1E3DF', name: On Surface}
      - {color: '#404943', name: Surface Variant}
      - {color: '#C0C9C1', name: On Surface Variant}
      - {color: '#8A938C', name: Outline}
      - {color: 'rgba(208, 232, 216, 0.2)', name: Dark Overlay 1}
      - {color: 'rgba(208, 232, 216, 0.5)', name: Dark Overlay 2}
      - {color: 'rgba(208, 232, 216, 0.2)', name: Light Overlay 1}
      - {color: 'rgba(208, 232, 216, 0.5)', name: Light Overlay 2}
      - {color: 'rgba(133, 133, 139, 0.12)', name: Disabled Container}
      - {color: '#85858B', name: On Disabled}
      - {color: 'rgba(30, 185, 128, 0.05)', name: Primary Overlay 1}
      - {color: 'rgba(30, 185, 128, 0.08)', name: Primary Overlay 2}
      - {color: 'rgba(30, 185, 128, 0.11)', name: Primary Overlay 3}
      name: Rally Dark
    - colors:
      - {color: '#006C48', name: Primary}
      - {color: '#00A36C', name: Primary Container}
      - {color: '#FFFFFF', name: On Primary}
      - {color: '#002113', name: On Primary Container}
      - {color: '#496455', name: Secondary}
      - {color: '#CBEAD6', name: Secondary Container}
      - {color: '#FFFFFF', name: On Secondary}
      - {color: '#052014', name: On Secondary Container}
      - {color: '#326576', name: Tertiary}
      - {color: '#B8EAFF', name: Tertiary Container}
      - {color: '#FFFFFF', name: On Tertiary}
      - {color: '#001F28', name: On Tertiary Container}
      - {color: '#D64D47', name: Error}
      - {color: '#FBFDF8', name: Background}
      - {color: '#FBFDF8', name: Surface}
      - {color: '#191C1A', name: On Background}
      - {color: '#191C1A', name: On Surface}
      - {color: '#DCE5DD', name: Surface Variant}
      - {color: '#404943', name: On Surface Variant}
      - {color: '#707973', name: Outline}
      - {color: 'rgba(5, 32, 20, 0.8)', name: Dark Overlay 1}
      - {color: 'rgba(51, 51, 61, 0.12)', name: Dark Overlay 2}
      - {color: 'rgba(255, 255, 255, 0.8)', name: Light Overlay 1}
      - {color: 'rgba(255, 255, 255, 0.12)', name: Light Overlay 2}
      - {color: 'rgba(25, 28, 26, 0.12)', name: Disabled Container}
      - {color: 'rgba(25, 28, 26, 0.38)', name: On Disabled}
      - {color: 'rgba(0, 108, 72, 0.05)', name: Primary Overlay 1}
      - {color: 'rgba(0, 108, 72, 0.08)', name: Primary Overlay 2}
      - {color: 'rgba(0, 108, 72, 0.11)', name: Primary Overlay 3}
      name: Rally Light
    - colors:
      - {color: '#006874', name: Primary}
      - {color: '#96F0FF', name: Primary Container}
      - {color: '#FFFFFF', name: On Primary}
      - {color: '#001F24', name: On Primary Container}
      - {color: '#486367', name: Secondary}
      - {color: '#CBE8ED', name: Secondary Container}
      - {color: '#FFFFFF', name: On Secondary}
      - {color: '#031F23', name: On Secondary Container}
      - {color: '#515E80', name: Tertiary}
      - {color: '#DAE2FF', name: Tertiary Container}
      - {color: '#FFFFFF', name: On Tertiary}
      - {color: '#0C1A39', name: On Tertiary Container}
      - {color: '#BA1A1A', name: Error}
      - {color: '#FAFDFD', name: Background}
      - {color: '#FAFDFD', name: Surface}
      - {color: '#191C1D', name: On Background}
      - {color: '#191C1D', name: On Surface}
      - {color: '#DBE4E6', name: Surface Variant}
      - {color: '#3F484A', name: On Surface Variant}
      - {color: '#6F797A', name: Outline}
      - {color: 'rgba(25, 28, 29, 0.38)', name: On Disabled}
      - {color: 'rgba(25, 28, 29, 0.12)', name: Disabled Container}
      - {color: 'rgba(255, 255, 255, 0.08)', name: Light Overlay 1}
      - {color: 'rgba(255, 255, 255, 0.12)', name: Light Overlay 2}
      - {color: 'rgba(3, 31, 35, 0.08)', name: Dark Overlay 1}
      - {color: 'rgba(3, 31, 35, 0.12)', name: Dark Overlay 2}
      - {color: 'rgba(0, 104, 116, 0.05)', name: Primary Overlay 1}
      - {color: 'rgba(0, 104, 116, 0.08)', name: Primary Overlay 2}
      - {color: 'rgba(0, 104, 116, 0.11)', name: Primary Overlay 3}
      name: Mykonos Light
    - colors:
      - {color: '#3CD9ED', name: Primary}
      - {color: '#004F57', name: Primary Container}
      - {color: '#00363D', name: On Primary}
      - {color: '#96F0FF', name: On Primary Container}
      - {color: '#AFCBD0', name: Secondary}
      - {color: '#314B4F', name: Secondary Container}
      - {color: '#1A3438', name: On Secondary}
      - {color: '#CBE8ED', name: On Secondary Container}
      - {color: '#B9C6ED', name: Tertiary}
      - {color: '#394667', name: Tertiary Container}
      - {color: '#23304F', name: On Tertiary}
      - {color: '##DAE2FF', name: On Tertiary Container}
      - {color: '#FFB4AB', name: Error}
      - {color: '#191C1D', name: Background}
      - {color: '#191C1D', name: Surface}
      - {color: '#E1E3E3', name: On Background}
      - {color: '#E1E3E3', name: On Surface}
      - {color: '#3F484A', name: Surface Variant}
      - {color: '#BFC8CA', name: On Surface Variant}
      - {color: '#899294', name: Outline}
      - {color: 'rgba(225, 227, 227, 0.38)', name: On Disabled}
      - {color: 'rgba(225, 227, 227, 0.12)', name: Disabled Container}
      - {color: 'rgba(203, 232, 237, 0.08)', name: Light Overlay 1}
      - {color: 'rgba(203, 232, 237, 0.12)', name: Light Overlay 2}
      - {color: 'rgba(203, 232, 237, 0.08)', name: Dark Overlay 1}
      - {color: 'rgba(203, 232, 237, 0.12)', name: Dark Overlay 2}
      - {color: 'rgba(60, 217, 237, 0.05)', name: Primary Overlay 1}
      - {color: 'rgba(60, 217, 237, 0.08)', name: Primary Overlay 2}
      - {color: 'rgba(60, 217, 237, 0.11)', name: Primary Overlay 3}
      name: Mykonos Dark
    - colors:
      - {color: '#9A4523', name: Primary}
      - {color: '#FFDBCF', name: Primary Container}
      - {color: '#FFFFFF', name: On Primary}
      - {color: '#380D00', name: On Primary Container}
      - {color: '#77574C', name: Secondary}
      - {color: '#FFDBCF', name: Secondary Container}
      - {color: '#FFFFFF', name: On Secondary}
      - {color: '#2C160D', name: On Secondary Container}
      - {color: '#695E2F', name: Tertiary}
      - {color: '#F2E2A7', name: Tertiary Container}
      - {color: '#FFFFFF', name: On Tertiary}
      - {color: '#221B00', name: On Tertiary Container}
      - {color: '#BA1A1A', name: Error}
      - {color: '#FFFBFF', name: Background}
      - {color: '#FFFBFF', name: Surface}
      - {color: '#201A18', name: On Background}
      - {color: '#201A18', name: On Surface}
      - {color: '#F5DED6', name: Surface Variant}
      - {color: '#53433E', name: On Surface Variant}
      - {color: '#85736D', name: Outline}
      - {color: 'rgba(32, 26, 24, 0.38)', name: On Disabled}
      - {color: 'rgba(32, 26, 24, 0.12)', name: Disabled Container}
      - {color: 'rgba(255, 255, 255, 0.08)', name: Light Overlay 1}
      - {color: 'rgba(255, 255, 255, 0.12)', name: Light Overlay 2}
      - {color: 'rgba(44, 22, 13, 0.08)', name: Dark Overlay 1}
      - {color: 'rgba(44, 22, 13, 0.12)', name: Dark Overlay 2}
      - {color: 'rgba(154, 69, 35, 0.05)', name: Primary Overlay 1}
      - {color: 'rgba(154, 69, 35, 0.08)', name: Primary Overlay 2}
      - {color: 'rgba(154, 69, 35, 0.11)', name: Primary Overlay 3}
      name: Manarola Light
    - colors:
      - {color: '#FFB59B', name: Primary}
      - {color: '#7B2E0E', name: Primary Container}
      - {color: '#5B1A00', name: On Primary}
      - {color: '#FFDBCF', name: On Primary Container}
      - {color: '#E7BDB0', name: Secondary}
      - {color: '#5D4036', name: Secondary Container}
      - {color: '#442A21', name: On Secondary}
      - {color: '#FFDBCF', name: On Secondary Container}
      - {color: '#D5C68E', name: Tertiary}
      - {color: '#50461A', name: Tertiary Container}
      - {color: '#393005', name: On Tertiary}
      - {color: '#F2E2A7', name: On Tertiary Container}
      - {color: '#FFB4AB', name: Error}
      - {color: '#201A18', name: Background}
      - {color: '#201A18', name: Surface}
      - {color: '#EDE0DC', name: On Background}
      - {color: '#EDE0DC', name: On Surface}
      - {color: '#53433E', name: Surface Variant}
      - {color: '#D8C2BB', name: On Surface Variant}
      - {color: '#A08D86', name: Outline}
      - {color: 'rgba(237, 224, 220, 0.38)', name: On Disabled}
      - {color: 'rgba(237, 224, 220, 0.12)', name: Disabled Container}
      - {color: 'rgba(255, 219, 207, 0.08)', name: Light Overlay 1}
      - {color: 'rgba(255, 219, 207, 0.12)', name: Light Overlay 2}
      - {color: 'rgba(255, 219, 207, 0.08)', name: Dark Overlay 1}
      - {color: 'rgba(255, 219, 207, 0.12)', name: Dark Overlay 2}
      - {color: 'rgba(255, 181, 155, 0.05)', name: Primary Overlay 1}
      - {color: 'rgba(255, 181, 155, 0.08)', name: Primary Overlay 2}
      - {color: 'rgba(255, 181, 155, 0.11)', name: Primary Overlay 3}
      name: Manarola Dark
roles:
- components: [Label]
  name: input-prompt
- components: [Link]
  name: selected
- components: [ColumnPanel, LinearPanel, XYPanel, RepeatingPanel]
  display_in_toolbox: false
  name: outlined-card
  title: Outlined Card
- components: [ColumnPanel, LinearPanel, XYPanel, RepeatingPanel]
  display_in_toolbox: false
  name: elevated-card
  title: Elevated Card
- components: [ColumnPanel, LinearPanel, XYPanel, RepeatingPanel]
  display_in_toolbox: false
  name: tonal-card
  title: Tonal Card
- components: [Button, FileLoader]
  display_in_toolbox: false
  name: outlined-button
  title: Outlined Button
- components: [Button, FileLoader]
  display_in_toolbox: false
  name: filled-button
  title: Filled Button
- components: [Button, FileLoader]
  display_in_toolbox: false
  name: elevated-button
  title: Elevated Button
- components: [Button, FileLoader]
  display_in_toolbox: false
  name: tonal-button
  title: Tonal Button
- components: [TextBox, TextArea, DatePicker, DropDown]
  display_in_toolbox: false
  name: outlined
  title: Outlined TextBox
- components: [Label, Link]
  name: display
- components: [Label, Link]
  name: headline
- components: [Label, Link]
  name: title
- components: [Label, Link]
  name: body
- components: [DataGrid]
  name: tonal-data-grid
- components: [TextBox, TextArea, DatePicker, DropDown]
  name: outlined-error
- components: [TextBox, TextArea, DatePicker, DropDown]
  name: input-error
- {name: message}
- {name: bot-message}
- {name: no-underline-textbox}
- {name: naked}
- {name: round-flow-panel}
- {name: richtext-powered}
- {name: load-message}
- {name: src-link}
- {name: fixed-repeating-panel}
- {name: cp-chatbubbles}
- {name: flag-button}
- {name: richtext-powered-small}
